/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MainSceneControl from "./script/MainSceneControl"
import Bucket from "./script/Bucket"
import Candy from "./script/Candy"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="center";
    static startScene:any="scene/MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=true;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/MainSceneControl.ts",MainSceneControl);
        reg("script/Bucket.ts",Bucket);
        reg("script/Candy.ts",Candy);
    }
}
GameConfig.init();