/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MainSceneControl from "./script/MainSceneControl"
import Candy from "./script/Candy"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="scene/MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=true;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/MainSceneControl.ts",MainSceneControl);
        reg("script/Candy.ts",Candy);
    }
}
GameConfig.init();